Implement skeleton component
js-tasks-ru/htmlcss-20231027_egor3 pull request #9
Opened 2023-11-10 11:49 UTC by DnEgorWeb

2023-11-10 11:50 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-10 11:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-12 14:21 UTC, GSemikozov requested changes

2023-11-12 14:21 UTC, GSemikozov commented on 04-lection2/02-skeleton/index.html
> +                        <div class="skeleton__line" style="width: 30%"></div>
вместо инлайна лучше создать 3 модификатора

2023-11-12 14:21 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +@import '../../assets/css/main.css';
не надо)

2023-11-12 17:11 UTC, DnEgorWeb commented on 04-lection2/02-skeleton/index.html
> +                        <div class="skeleton__line" style="width: 30%"></div>
Исправил на модификаторы

2023-11-12 17:11 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-12 17:11 UTC, DnEgorWeb commented on 04-lection2/02-skeleton/skeleton.css
> +@import '../../assets/css/main.css';
Убрал)

2023-11-12 17:18 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-15 22:06 UTC, GSemikozov approved these changes

2023-11-15 22:06 UTC, merged